---
- name: Configure OPS445 VM for Labs
  hosts: vmlab
  become: yes

  vars:
    seneca_id: hshah104
    ssh_pub_key: "{{ lookup('file', '/home/oem/.ssh/id_ed25519.pub') }}"
    lab_dirs:
      - lab1
      - lab2
      - lab3
      - lab4
      - lab5
      - lab6
      - lab7
      - lab8

  tasks:
    - name: Ensure Apache is installed and updated
      yum:
        name: httpd
        state: latest

    - name: Ensure EPEL repo is installed
      yum:
        name: epel-release
        state: present

    - name: Remove 'tree' package if it exists
      yum:
        name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create user with Seneca ID
      user:
        name: "{{ seneca_id }}"
        groups: wheel
        append: yes
        shell: /bin/bash
        state: present

    - name: Allow passwordless SSH for new user
      authorized_key:
        user: "{{ seneca_id }}"
        key: "{{ ssh_pub_key }}"

    - name: Create ops445 lab directories for new user
      file:
        path: "/home/{{ seneca_id }}/ops445/{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ lab_dirs }}"
